### ISSUE TITLE
More planter boxes for more purposes.

### ISSUE THREAD

**Issue by bongbongsaysbong** [teamhollow/readyyourshovels#5]
Currently, planter boxes are intended to grow crops; wheat, carrots, potatoes, beetroot. I don't know if this is intentional, but you can grow these crops in the Nether. However, a few growable plants are still missing; sugar cane. Sugar cane requires a water source block next to it to grow. Cacti. Cacti grow slower in the Nether, but I could be wrong on this one. Finally, bamboo; bamboo grows slower in the Nether, but again, I could be wrong.

I suggest adding a new type of planter box, which holds sand and is used to grow cacti & sugar cane, and allowing bamboo to grow in normal planter boxes. Perhaps the sand texture of the sand in sandy planter boxes could be wet, to indicate that it's full of water and able to grow sugar cane. This might not make sense in the Nether, but placing water in a cauldron works (though it can't be used for hosting life), so it's not too much of a stretch.

On the other hand, cacti might be able to already be grown in the Nether; if this is the case, then a simpler alternative would just be to allow sugar cane to grow in normal planter boxes. However, if this is added, I think that it could greatly benefit Planter Boxes; perhaps it opens new avenues like Soul Sand Planter Boxes which grow Nether Wart at a faster rate, or even other mod integration for their custom crops.

**Comment by dvitski** [comment]
The above commit has made it so that planter boxes now can be filled with either dirt or sand, allowing seed or sugar cane placement respectively!
We may implement more of your suggestions at a later date as well 👍
