### ISSUE TITLE
(Forge 1.16.5) Crash on world load

### ISSUE THREAD

**Issue by dabomb6405** [teamhollow/readyyourshovels#6]
Whenever I start a world, new or premade, the game crashes. Not really sure what to do, but here's a crash report.
[crash-2021-02-07_19.34.34-server.txt](https://github.com/teamhollow/readyyourshovels/files/5940986/crash-2021-02-07_19.34.34-server.txt)

**Comment by dvitski** [comment]
The Forge version of this mod is extremely out of date and won't be ported to until near the full release of Ready Your Shovels :P

May I ask where you got this version from as I don't recognise a portion of the code shown in the crash report?

**Comment by dabomb6405** [comment]
Oh, I just compiled it from here.

**Comment by dvitski** [comment]
Oh, yeah that definitely won't work as intended lmao

Thanks for reporting, anyways! :D
